version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
#        build: 
#          context: .
#          dockerfile: Dockerfile
        env_file:
          - sqlserver.env
          - sapassword.env
        ports:
          - 1433:1433
        volumes:
          - ./stack-overflow/StackOverflow2013_201809117/:/stack-overflow/