version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "P@55w0rd"
            ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        volumes:
          - ./stack-overflow/StackOverflow2013_201809117/:/stack-overflow/